### ISSUE TITLE
将 Github Pages 地址放在首页上

### ISSUE THREAD

**Issue by jizusun** [redbearder/The-Site-Reliability-Workbook-CHS#1]
厉害哇！
大佬是全手动翻译的，还是机器翻译结合手动翻译进行的？

**Comment by redbearder** [comment]
> 厉害哇！
> 大佬是全手动翻译的，还是机器翻译结合手动翻译进行的？

看一段，翻译一段，然后机翻一下，校对机翻，两端比较结合一下，定稿
说实话，我觉得大部分机翻用词比我自己的好多了

**Comment by jizusun** [comment]
> > 厉害哇！
> > 大佬是全手动翻译的，还是机器翻译结合手动翻译进行的？
> 
> 看一段，翻译一段，然后机翻一下，校对机翻，两端比较结合一下，定稿
> 说实话，我觉得大部分机翻用词比我自己的好多了

哇，那用了很久是吗？

> 放在首页

我是指这里

![image](https://user-images.githubusercontent.com/4011348/94359002-1aa63180-00d7-11eb-9b31-1aa40b02728f.png)

**Comment by redbearder** [comment]
> > > 厉害哇！
> > > 大佬是全手动翻译的，还是机器翻译结合手动翻译进行的？
> > 
> > 
> > 看一段，翻译一段，然后机翻一下，校对机翻，两端比较结合一下，定稿
> > 说实话，我觉得大部分机翻用词比我自己的好多了
> 
> 哇，那用了很久是吗？
> 
> > 放在首页
> 
> 我是指这里
> 
> ![image](https://user-images.githubusercontent.com/4011348/94359002-1aa63180-00d7-11eb-9b31-1aa40b02728f.png)

放好了，谢谢

还是用了挺久的，晚上基本都干这个了，干到后半夜

**Comment by jizusun** [comment]
我也对SRE挺感兴趣的，大佬还有啥翻译的，求带上我哇~

**Comment by redbearder** [comment]
> 我也对SRE挺感兴趣的，大佬还有啥翻译的，求带上我哇~

嗨，哪有那么多需要翻译的，我这次完全是心血来潮+最近事不多，顺便把这本书看完，哈哈哈
