### ISSUE TITLE
Typo: 11_附录B-错误预算政策示例

### ISSUE THREAD

**Issue by HackettYu** [redbearder/The-Site-Reliability-Workbook-CHS#3]
> https://github.com/redbearder/The-Site-Reliability-Workbook-CHS/blob/master/11_附录B-错误预算政策示例.md

这个标题的翻译可能打错字了

```diff
-**SLO小姐政策**
+**SLO小组政策** or +**SLO团队政策**

如果服务在其SLO或更高的性能下运行，则将根据发布策略继续进行发布（包括数据更改）。

如果该服务超出了前四个星期的错误预算，我们将停止所有更改并发布P0 [^116]问题或安全修补程序以外的其他问题，直到该服务返回其SLO之内。
```

**Comment by redbearder** [comment]
> > [https://github.com/redbearder/The-Site-Reliability-Workbook-CHS/blob/master/11_附录B-错误预算政策示例.md](https://github.com/redbearder/The-Site-Reliability-Workbook-CHS/blob/master/11_%E9%99%84%E5%BD%95B-%E9%94%99%E8%AF%AF%E9%A2%84%E7%AE%97%E6%94%BF%E7%AD%96%E7%A4%BA%E4%BE%8B.md)
> 
> 这个标题的翻译可能打错字了
> 
> ```diff
> -**SLO小姐政策**
> +**SLO小组政策** or +**SLO团队政策**
> 
> 如果服务在其SLO或更高的性能下运行，则将根据发布策略继续进行发布（包括数据更改）。
> 
> 如果该服务超出了前四个星期的错误预算，我们将停止所有更改并发布P0 [^116]问题或安全修补程序以外的其他问题，直到该服务返回其SLO之内。
> ```

貌似不经意间暴露了什么信息啊， 哈哈哈
